name: deploy-workdir

on:
  push: 
    branches:
      - master
    paths: 
     - 'workdir/**'

defaults: 
  run:
    working-directory: workdir

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_I60_S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_I60_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: "workdir"
      # - uses: shinyinc/action-aws-cli@v1.2
      # - run: aws s3 sync dist s3://${{secrets.AWS_I60_S3_BUCKET_NAME}}
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_I60_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
      #     AWS_DEFAULT_REGION: 'us-east-2'

      - run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_I60_DISTRIBUTION_ID}} --paths "/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'us-east-2'