name: deploy-workdir

on:
  push: 
    branches:
      - master
    paths: 
     - 'workdir/**'

defaults: 
  run:
    working-directory: workdir

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_I60_S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_I60_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-2'

      - run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_I60_DISTRIBUTION_ID}} --paths "/workdir/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_I60_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'us-east-2' 